"""Setup.py module for the Material-Model plugin."""
# WARNING - DO NOT EDIT - YOUR CHANGES WILL NOT BE PROTECTED.
# This file is auto-generated by the aac gen-plugin and may be overwritten.

from setuptools import find_packages, setup

with open("README.md", "r") as fh:
    readme_description = fh.read()

runtime_dependencies = [
    "aac ~= 0.2.0"
]

development_dependencies = [
    "pipdeptree ~= 2.13.0",
    "wheel ~= 0.41.0",
    "pip-tools >= 6.9.0",
]

test_dependencies = [
    "tox >= 3.24",
    "nose2 ~= 0.10.0",
    "coverage ~= 6.0",
    "flake8 ~= 4.0",
    "flake8-docstrings ~= 1.6.0",
    "flake8-fixme ~= 1.1.1",
    "flake8-eradicate ~= 1.2.0",
    "flake8-assertive ~= 1.3.0",
]

setup(
    version="0.0.1",
    name="aac-bom",
    description=(
        "Architecture-as-Code (AaC) plugin for material modeling.  Rigorously track your sites, assemblies, and parts."
    ),
    license="MIT",
    packages=find_packages(where=".", exclude="tests"),
    package_data={"": ["*.aac", "*.jinja2", "*.yaml"]},
    install_requires=runtime_dependencies,
    extras_require={
        "dev": development_dependencies,
        "test": test_dependencies,
        "all": development_dependencies + test_dependencies,
    },
    entry_points={
        "aac": ["Material-Model=material_model"],
    }
)
